"""
report_generator.py
Generates professional PDF incident response reports using fpdf2.
Each report covers alert summary, enrichment data, severity decision,
containment actions, ticket details, and notification status.
"""

from fpdf import FPDF
from datetime import datetime


class IncidentReportPDF(FPDF):
    """Custom FPDF subclass for SecFlow incident reports."""

    NAVY = (20, 30, 70)
    DARK_BG = (30, 40, 80)
    WHITE = (255, 255, 255)
    LIGHT_GRAY = (245, 245, 250)
    MID_GRAY = (200, 200, 210)
    TEXT_DARK = (30, 30, 50)
    TEXT_SECONDARY = (100, 100, 120)

    SEVERITY_COLORS = {
        "critical": (220, 50, 50),
        "high": (240, 140, 30),
        "medium": (230, 200, 40),
        "low": (60, 180, 80),
    }

    def header(self):
        # Dark header band
        self.set_fill_color(*self.NAVY)
        self.rect(0, 0, 210, 36, "F")

        # Logo text
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*self.WHITE)
        self.set_xy(12, 8)
        self.cell(0, 8, "SecFlow Engine", new_x="LMARGIN", new_y="NEXT")

        # Subtitle
        self.set_font("Helvetica", "", 9)
        self.set_text_color(180, 190, 220)
        self.set_xy(12, 18)
        self.cell(0, 6, "INCIDENT RESPONSE REPORT", new_x="LMARGIN", new_y="NEXT")

        # Timestamp aligned right
        self.set_font("Helvetica", "", 7)
        self.set_text_color(160, 170, 200)
        self.set_xy(12, 26)
        self.cell(
            0,
            6,
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        self.set_y(42)

    def footer(self):
        self.set_y(-16)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.cell(0, 6, "Generated by SecFlow Engine", align="L")
        self.cell(0, 6, f"Page {self.page_no()}/{{nb}}", align="R")

    def section_title(self, number, title):
        """Renders a styled section heading."""
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.NAVY)
        self.cell(0, 8, f"  {number}.  {title}", new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_draw_color(*self.MID_GRAY)
        self.set_line_width(0.3)
        y = self.get_y()
        self.line(10, y, 200, y)
        self.ln(3)

    def info_row(self, label, value, row_index=0):
        """Renders a label-value row with alternating background shading."""
        if row_index % 2 == 0:
            self.set_fill_color(*self.LIGHT_GRAY)
        else:
            self.set_fill_color(*self.WHITE)

        y = self.get_y()
        self.rect(10, y, 190, 7, "F")

        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*self.TEXT_DARK)
        self.set_xy(14, y)
        self.cell(55, 7, str(label))

        self.set_font("Helvetica", "", 8)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.set_xy(69, y)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def severity_badge(self, severity):
        """Draws a colored severity indicator badge."""
        color = self.SEVERITY_COLORS.get(severity.lower(), (150, 150, 150))
        y = self.get_y()

        # Badge background
        self.set_fill_color(*color)
        badge_text = severity.upper()
        badge_width = self.get_string_width(badge_text) + 10
        self.set_xy(69, y)
        self.rect(69, y + 1, badge_width, 6, "F")

        # Badge text
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*self.WHITE)
        self.set_xy(69, y)
        self.cell(badge_width, 7, f"  {badge_text}  ", align="C")
        self.ln(8)


def _safe(data, *keys, default="N/A"):
    """Safely traverse nested dict keys, returning default if missing."""
    current = data
    for key in keys:
        if isinstance(current, dict):
            current = current.get(key, None)
        else:
            return default
        if current is None:
            return default
    return current if current not in (None, "", {}, []) else default


def generate_incident_pdf(alert_id: str, run_log: dict, ticket: dict) -> bytes:
    """
    Generates a professional PDF incident response report.

    Args:
        alert_id: The alert identifier.
        run_log: The playbook run log dictionary.
        ticket: The ticket record dictionary from SQLite.

    Returns:
        Raw PDF bytes.
    """
    pdf = IncidentReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()

    steps = run_log.get("steps", {})
    enrich = steps.get("enrich", {})
    decide = steps.get("decide", {})
    contain = steps.get("contain", {})
    notify_step = steps.get("notify", {})

    # ── Section 1: Alert Summary ──
    pdf.section_title("1", "Alert Summary")
    rows_1 = [
        ("Alert ID", alert_id),
        ("Playbook", _safe(run_log, "playbook")),
        ("Started At", _safe(run_log, "started_at")),
        ("Finished At", _safe(run_log, "finished_at")),
        ("Result", _safe(run_log, "result")),
    ]
    for i, (label, value) in enumerate(rows_1):
        pdf.info_row(label, value, i)
    pdf.ln(6)

    # ── Section 2: Enrichment Results ──
    pdf.section_title("2", "Enrichment Results")
    rows_2 = [
        ("IP Address", _safe(enrich, "ip")),
        ("Abuse Confidence Score", _safe(enrich, "abuseConfidenceScore")),
        ("Country Code", _safe(enrich, "countryCode")),
        ("ISP", _safe(enrich, "isp")),
        ("Total Reports", _safe(enrich, "totalReports")),
        ("Source", _safe(enrich, "source", default="AbuseIPDB")),
    ]
    for i, (label, value) in enumerate(rows_2):
        pdf.info_row(label, value, i)
    pdf.ln(6)

    # ── Section 3: Severity Decision ──
    pdf.section_title("3", "Severity Decision")
    severity = str(_safe(decide, "severity", default="unknown"))
    pdf.info_row("Severity Level", "", 0)
    pdf.set_y(pdf.get_y() - 7)
    pdf.severity_badge(severity)
    pdf.ln(2)

    # ── Section 4: Containment Actions ──
    pdf.section_title("4", "Containment Actions")
    rows_4 = [
        ("Status", _safe(contain, "status")),
        ("Command Executed", _safe(contain, "command")),
    ]
    reason = _safe(contain, "reason")
    if reason != "N/A":
        rows_4.append(("Reason (Skipped)", reason))
    for i, (label, value) in enumerate(rows_4):
        pdf.info_row(label, value, i)
    pdf.ln(6)

    # ── Section 5: Ticket Details ──
    pdf.section_title("5", "Ticket Details")
    rows_5 = [
        ("Ticket ID", _safe(ticket, "id", default=_safe(ticket, "ticket_id"))),
        ("Status", _safe(ticket, "status")),
        ("Created At", _safe(ticket, "created_at")),
        ("Summary", _safe(ticket, "summary")),
        ("Merged", str(_safe(ticket, "merged", default="N/A"))),
    ]
    for i, (label, value) in enumerate(rows_5):
        pdf.info_row(label, value, i)
    pdf.ln(6)

    # ── Section 6: Notification ──
    pdf.section_title("6", "Notification")
    notify_sent = _safe(notify_step, "sent", default="N/A")
    notify_note = _safe(notify_step, "note")
    rows_6 = [
        ("Sent", str(notify_sent)),
        ("Note", notify_note),
    ]
    for i, (label, value) in enumerate(rows_6):
        pdf.info_row(label, value, i)

    return pdf.output()
