"""
ticketing.py
Simple local ticket queue backed by SQLite. Stands in for a real
ticketing system (Jira/GLPI/ServiceNow) -- swap execute() calls here
for an API request if you wire this into a real one later.
"""

import sqlite3
import os
import datetime
import requests

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "evidence", "tickets.db")


def _init_db():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS tickets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_id TEXT,
            indicator TEXT,
            severity TEXT,
            status TEXT,
            created_at TEXT,
            summary TEXT
        )
        """
    )
    conn.commit()
    return conn


def open_ticket(alert_id: str, indicator: str, severity: str, summary: str) -> dict:
    conn = _init_db()
    
    # Deduplication check: check if an open ticket for the same alert_id and indicator already exists
    cursor = conn.execute(
        "SELECT id, created_at, summary FROM tickets WHERE alert_id = ? AND indicator = ? AND status = 'open'",
        (alert_id, indicator)
    )
    row = cursor.fetchone()
    if row:
        ticket_id, created_at, existing_summary = row[0], row[1], row[2]
        conn.close()
        return {
            "ticket_id": ticket_id,
            "status": "open",
            "created_at": created_at,
            "merged": True
        }

    created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # GitHub Issues Escalation Logic
    git_token = os.getenv("GITHUB_TOKEN")
    git_repo = os.getenv("GITHUB_REPO")
    
    if git_token and git_repo and severity in ["high", "critical"]:
        try:
            url = f"https://api.github.com/repos/{git_repo}/issues"
            headers = {
                "Authorization": f"token {git_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            body = (
                f"### ⚡ SecFlow SOAR Incident Report\n\n"
                f"- **Alert ID**: `{alert_id}`\n"
                f"- **Indicator (IP)**: `{indicator}`\n"
                f"- **Severity**: `{severity.upper()}`\n"
                f"- **Host**: `{summary.split('host ')[1].split(':')[0] if 'host ' in summary else 'N/A'}`\n"
                f"- **Description**: {summary}\n"
                f"- **Timestamp**: `{created_at}`\n\n"
                f"*Automated ticket generated by SecFlow Engine playbooks.*"
            )
            payload = {
                "title": f"[Incident Alert] {severity.upper()} - {alert_id} | IP {indicator}",
                "body": body,
                "labels": ["incident", severity]
            }
            resp = requests.post(url, json=payload, headers=headers, timeout=5)
            if resp.status_code == 201:
                git_issue_url = resp.json().get("html_url")
                summary = f"{summary} | GitHub Ref: {git_issue_url}"
        except Exception as e:
            # Silent fallback to prevent halting execution if GitHub API fails
            print(f"[-] GitHub escalation failed: {e}")

    cur = conn.execute(
        "INSERT INTO tickets (alert_id, indicator, severity, status, created_at, summary) "
        "VALUES (?, ?, ?, 'open', ?, ?)",
        (alert_id, indicator, severity, created_at, summary),
    )
    conn.commit()
    ticket_id = cur.lastrowid
    conn.close()
    return {
        "ticket_id": ticket_id,
        "status": "open",
        "created_at": created_at,
        "merged": False
    }
