"""
ticketing.py
Simple local ticket queue backed by SQLite. Stands in for a real
ticketing system (Jira/GLPI/ServiceNow) -- swap execute() calls here
for an API request if you wire this into a real one later.
"""

import sqlite3
import os
import datetime
import requests

try:
    import dotenv
except ImportError:
    dotenv = None

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "evidence", "tickets.db")


def _init_db():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS tickets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            alert_id TEXT,
            indicator TEXT,
            severity TEXT,
            status TEXT,
            created_at TEXT,
            summary TEXT
        )
        """
    )
    conn.commit()
    return conn


def open_ticket(alert_id: str, indicator: str, severity: str, summary: str) -> dict:
    # Load .env so Jira and GitHub env vars are available
    if dotenv:
        env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
        if os.path.exists(env_path):
            dotenv.load_dotenv(env_path, override=True)

    conn = _init_db()
    
    # Deduplication check: check if an open ticket for the same alert_id and indicator already exists
    cursor = conn.execute(
        "SELECT id, created_at, summary FROM tickets WHERE alert_id = ? AND indicator = ? AND status = 'open'",
        (alert_id, indicator)
    )
    row = cursor.fetchone()
    if row:
        ticket_id, created_at, existing_summary = row[0], row[1], row[2]
        conn.close()
        return {
            "ticket_id": ticket_id,
            "status": "open",
            "created_at": created_at,
            "merged": True
        }

    created_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # GitHub Issues Escalation Logic
    git_token = os.getenv("GITHUB_TOKEN")
    git_repo = os.getenv("GITHUB_REPO")
    
    if git_repo:
        git_repo = git_repo.strip()
        # If user entered the full URL, e.g., https://github.com/owner/repo
        if "github.com/" in git_repo:
            parts = git_repo.split("github.com/")
            if len(parts) > 1:
                git_repo = parts[1].strip("/")
                # Clean up query params if any
                git_repo = git_repo.split("?")[0]
                # Clean up .git suffix if any
                if git_repo.endswith(".git"):
                    git_repo = git_repo[:-4]
                    
    if git_token and git_repo and severity in ["high", "critical"]:
        try:
            url = f"https://api.github.com/repos/{git_repo}/issues"
            headers = {
                "Authorization": f"token {git_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            body = (
                f"### ⚡ SecFlow SOAR Incident Report\n\n"
                f"- **Alert ID**: `{alert_id}`\n"
                f"- **Indicator (IP)**: `{indicator}`\n"
                f"- **Severity**: `{severity.upper()}`\n"
                f"- **Host**: `{summary.split('host ')[1].split(':')[0] if 'host ' in summary else 'N/A'}`\n"
                f"- **Description**: {summary}\n"
                f"- **Timestamp**: `{created_at}`\n\n"
                f"*Automated ticket generated by SecFlow Engine playbooks.*"
            )
            payload = {
                "title": f"[Incident Alert] {severity.upper()} - {alert_id} | IP {indicator}",
                "body": body,
                "labels": ["incident", severity]
            }
            resp = requests.post(url, json=payload, headers=headers, timeout=5)
            if resp.status_code == 201:
                git_issue_url = resp.json().get("html_url")
                summary = f"{summary} | GitHub Ref: {git_issue_url}"
        except Exception as e:
            # Silent fallback to prevent halting execution if GitHub API fails
            print(f"[-] GitHub escalation failed: {e}")

    # Jira Escalation Logic
    jira_url = os.getenv('JIRA_BASE_URL')
    jira_email = os.getenv('JIRA_EMAIL')
    jira_token = os.getenv('JIRA_API_TOKEN')
    jira_project = os.getenv('JIRA_PROJECT_KEY')

    if jira_url and jira_email and jira_token and jira_project and severity in ['high', 'critical']:
        try:
            from requests.auth import HTTPBasicAuth
            api_endpoint = f'{jira_url.rstrip("/")}/rest/api/3/issue'
            jira_payload = {
                'fields': {
                    'project': {'key': jira_project},
                    'summary': f'[SecFlow] {severity.upper()} - {alert_id} | IP {indicator}',
                    'description': {
                        'type': 'doc',
                        'version': 1,
                        'content': [{
                            'type': 'paragraph',
                            'content': [{'type': 'text', 'text': summary}]
                        }]
                    },
                    'issuetype': {'name': 'Task'}
                }
            }
            resp = requests.post(
                api_endpoint,
                json=jira_payload,
                auth=HTTPBasicAuth(jira_email, jira_token),
                headers={'Content-Type': 'application/json'},
                timeout=10
            )
            if resp.status_code == 201:
                jira_key = resp.json().get('key', '')
                summary = f'{summary} | Jira: {jira_key}'
        except Exception as e:
            print(f'[-] Jira escalation failed: {e}')

    cur = conn.execute(
        "INSERT INTO tickets (alert_id, indicator, severity, status, created_at, summary) "
        "VALUES (?, ?, ?, 'open', ?, ?)",
        (alert_id, indicator, severity, created_at, summary),
    )
    conn.commit()
    ticket_id = cur.lastrowid
    conn.close()
    return {
        "ticket_id": ticket_id,
        "status": "open",
        "created_at": created_at,
        "merged": False
    }
